name: Cross-platform .NET Build with Multiple Versions

on:
  workflow_dispatch:

jobs:
  the-OS-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet_version: [7.0, 6.0, 5.0]
        
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet_version }}
