name: Send Email Notification Main Merge

on:
  pull_request:
    types:
      - closed

jobs:
  send-email-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Check if merged to main
      id: check_merge
      run: echo "is_merged=${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}"

    - name: Send Email Notification
      if: steps.check_merge.outputs.is_merged == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{ secrets.MAIL_CONNECTION }}
        subject: 'Merge to Main Alert'
        to: ${{ secrets.RECEIVER_EMAIL_USERNAME }}
        from: Luke Skywalker
        body: 'Someone has merged a pull request into the main branch. Check it on GitHub.'


   
