name: Send Email Notification

on:
  pull_request:
    types:
      - closed

jobs:
  send-email-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Send Email
      uses: hilarion5/send-mail@v1
      with:
        smtp-server: ${{ secrets.EMAIL_SERVER }}
        smtp-port: ${{ secrets.EMAIL_PORT }}
        smtp-secure: true
        from-email: ${{ secrets.SENDER_EMAIL_USERNAME }}
        to-email: ${{ secrets.RECEIVER_EMAIL_USERNAME }}
        username: ${{ secrets.SENDER_EMAIL_USERNAME }}
        password: ${{ secrets.SENDER_EMAIL_PASSWORD }}
        subject: Github Merge
        body: Someone has merged a pull request into the main branch. Check it on GitHub.
